## Importing Packages

In [11]:
# 패키지 설치 복습
pip install requests

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests) (1.25.10)
WARNING: You are using pip version 21.1.2; however, version 22.2.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
# import pymysql
from sqlalchemy import create_engine
# pymysql.install_as_MySQLdb()
# import MySQLdb
import numpy as np
import scipy
import warnings
warnings.filterwarnings(action='ignore')
import matplotlib.pyplot as plt
import requests
import json

import datetime as dt
from datetime import timedelta

import pycaret
import numba

# import telegram

## API Connect

### football-data API 연결

In [16]:
url = 'https://api.football-data.org/v4/competitions/PL'
headers = { 'X-Auth-Token': '69e8de15ccd446eda5dd611734693043' }
response = requests.get(url, headers=headers)
print(response.json())

{'area': {'id': 2072, 'name': 'England', 'code': 'ENG', 'flag': 'https://crests.football-data.org/770.svg'}, 'id': 2021, 'name': 'Premier League', 'code': 'PL', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/PL.png', 'currentSeason': {'id': 1490, 'startDate': '2022-08-05', 'endDate': '2023-05-28', 'currentMatchday': 1, 'winner': None}, 'seasons': [{'id': 1490, 'startDate': '2022-08-05', 'endDate': '2023-05-28', 'currentMatchday': 1, 'winner': None}, {'id': 733, 'startDate': '2021-08-13', 'endDate': '2022-05-22', 'currentMatchday': 38, 'winner': None}, {'id': 619, 'startDate': '2020-09-12', 'endDate': '2021-05-23', 'currentMatchday': 38, 'winner': {'id': 65, 'name': 'Manchester City FC', 'shortName': 'Man City', 'tla': 'MCI', 'crest': 'https://crests.football-data.org/65.png', 'address': 'SportCity Manchester M11 3FF', 'website': 'https://www.mancity.com', 'founded': 1880, 'clubColors': 'Sky Blue / White', 'venue': 'Etihad Stadium', 'lastUpdated': '2022-02-10T19:48:37Z'}}, {'id': 468, 'startDate': '2019-08-09', 'endDate': '2020-07-26', 'currentMatchday': 38, 'winner': {'id': 64, 'name': 'Liverpool FC', 'shortName': 'Liverpool', 'tla': 'LIV', 'crest': 'https://crests.football-data.org/64.png', 'address': 'Anfield Road Liverpool L4 0TH', 'website': 'http://www.liverpoolfc.tv', 'founded': 1892, 'clubColors': 'Red / White', 'venue': 'Anfield', 'lastUpdated': '2022-02-10T19:30:22Z'}}, {'id': 151, 'startDate': '2018-08-10', 'endDate': '2019-05-12', 'currentMatchday': 38, 'winner': {'id': 65, 'name': 'Manchester City FC', 'shortName': 'Man City', 'tla': 'MCI', 'crest': 'https://crests.football-data.org/65.png', 'address': 'SportCity Manchester M11 3FF', 'website': 'https://www.mancity.com', 'founded': 1880, 'clubColors': 'Sky Blue / White', 'venue': 'Etihad Stadium', 'lastUpdated': '2022-02-10T19:48:37Z'}}, {'id': 23, 'startDate': '2017-08-11', 'endDate': '2018-05-13', 'currentMatchday': 38, 'winner': {'id': 65, 'name': 'Manchester City FC', 'shortName': 'Man City', 'tla': 'MCI', 'crest': 'https://crests.football-data.org/65.png', 'address': 'SportCity Manchester M11 3FF', 'website': 'https://www.mancity.com', 'founded': 1880, 'clubColors': 'Sky Blue / White', 'venue': 'Etihad Stadium', 'lastUpdated': '2022-02-10T19:48:37Z'}}, {'id': 256, 'startDate': '2016-08-13', 'endDate': '2017-05-21', 'currentMatchday': None, 'winner': {'id': 61, 'name': 'Chelsea FC', 'shortName': 'Chelsea', 'tla': 'CHE', 'crest': 'https://crests.football-data.org/61.png', 'address': 'Fulham Road London SW6 1HS', 'website': 'http://www.chelseafc.com', 'founded': 1905, 'clubColors': 'Royal Blue / White', 'venue': 'Stamford Bridge', 'lastUpdated': '2022-02-10T19:24:40Z'}}, {'id': 257, 'startDate': '2015-08-08', 'endDate': '2016-05-17', 'currentMatchday': None, 'winner': {'id': 338, 'name': 'Leicester City FC', 'shortName': 'Leicester City', 'tla': 'LEI', 'crest': 'https://crests.football-data.org/338.png', 'address': 'The Walkers Stadium, Filbert Way Leicester LE2 7FL', 'website': 'http://www.lcfc.com', 'founded': 1884, 'clubColors': 'Royal Blue / White', 'venue': 'King Power Stadium', 'lastUpdated': '2022-02-10T19:48:23Z'}}, {'id': 258, 'startDate': '2014-08-16', 'endDate': '2015-05-24', 'currentMatchday': None, 'winner': {'id': 61, 'name': 'Chelsea FC', 'shortName': 'Chelsea', 'tla': 'CHE', 'crest': 'https://crests.football-data.org/61.png', 'address': 'Fulham Road London SW6 1HS', 'website': 'http://www.chelseafc.com', 'founded': 1905, 'clubColors': 'Royal Blue / White', 'venue': 'Stamford Bridge', 'lastUpdated': '2022-02-10T19:24:40Z'}}, {'id': 259, 'startDate': '2013-08-17', 'endDate': '2014-05-11', 'currentMatchday': None, 'winner': {'id': 65, 'name': 'Manchester City FC', 'shortName': 'Man City', 'tla': 'MCI', 'crest': 'https://crests.football-data.org/65.png', 'address': 'SportCity Manchester M11 3FF', 'website': 'https://www.mancity.com', 'founded': 1880, 'clubColors': 'Sky Blue / White', 'venue': 'Etihad Stadium', 'lastUpdated': '2022-02-10T19:48:37Z'}}, {'id': 260, 'startDate': '2012-08-18', 'endDate': '2013-05-19', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 261, 'startDate': '2011-08-13', 'endDate': '2012-05-13', 'currentMatchday': None, 'winner': {'id': 65, 'name': 'Manchester City FC', 'shortName': 'Man City', 'tla': 'MCI', 'crest': 'https://crests.football-data.org/65.png', 'address': 'SportCity Manchester M11 3FF', 'website': 'https://www.mancity.com', 'founded': 1880, 'clubColors': 'Sky Blue / White', 'venue': 'Etihad Stadium', 'lastUpdated': '2022-02-10T19:48:37Z'}}, {'id': 262, 'startDate': '2010-08-14', 'endDate': '2011-05-22', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 263, 'startDate': '2009-08-15', 'endDate': '2010-05-09', 'currentMatchday': None, 'winner': {'id': 61, 'name': 'Chelsea FC', 'shortName': 'Chelsea', 'tla': 'CHE', 'crest': 'https://crests.football-data.org/61.png', 'address': 'Fulham Road London SW6 1HS', 'website': 'http://www.chelseafc.com', 'founded': 1905, 'clubColors': 'Royal Blue / White', 'venue': 'Stamford Bridge', 'lastUpdated': '2022-02-10T19:24:40Z'}}, {'id': 264, 'startDate': '2008-08-16', 'endDate': '2009-05-24', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 265, 'startDate': '2007-08-11', 'endDate': '2008-05-11', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 266, 'startDate': '2006-08-19', 'endDate': '2007-05-13', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 267, 'startDate': '2005-08-13', 'endDate': '2006-05-07', 'currentMatchday': None, 'winner': {'id': 61, 'name': 'Chelsea FC', 'shortName': 'Chelsea', 'tla': 'CHE', 'crest': 'https://crests.football-data.org/61.png', 'address': 'Fulham Road London SW6 1HS', 'website': 'http://www.chelseafc.com', 'founded': 1905, 'clubColors': 'Royal Blue / White', 'venue': 'Stamford Bridge', 'lastUpdated': '2022-02-10T19:24:40Z'}}, {'id': 268, 'startDate': '2004-08-14', 'endDate': '2005-05-15', 'currentMatchday': None, 'winner': {'id': 61, 'name': 'Chelsea FC', 'shortName': 'Chelsea', 'tla': 'CHE', 'crest': 'https://crests.football-data.org/61.png', 'address': 'Fulham Road London SW6 1HS', 'website': 'http://www.chelseafc.com', 'founded': 1905, 'clubColors': 'Royal Blue / White', 'venue': 'Stamford Bridge', 'lastUpdated': '2022-02-10T19:24:40Z'}}, {'id': 269, 'startDate': '2003-08-16', 'endDate': '2004-05-15', 'currentMatchday': None, 'winner': {'id': 57, 'name': 'Arsenal FC', 'shortName': 'Arsenal', 'tla': 'ARS', 'crest': 'https://crests.football-data.org/57.png', 'address': '75 Drayton Park London N5 1BU', 'website': 'http://www.arsenal.com', 'founded': 1886, 'clubColors': 'Red / White', 'venue': 'Emirates Stadium', 'lastUpdated': '2022-02-10T19:48:56Z'}}, {'id': 270, 'startDate': '2002-08-17', 'endDate': '2003-05-11', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 271, 'startDate': '2001-08-18', 'endDate': '2002-05-11', 'currentMatchday': None, 'winner': {'id': 57, 'name': 'Arsenal FC', 'shortName': 'Arsenal', 'tla': 'ARS', 'crest': 'https://crests.football-data.org/57.png', 'address': '75 Drayton Park London N5 1BU', 'website': 'http://www.arsenal.com', 'founded': 1886, 'clubColors': 'Red / White', 'venue': 'Emirates Stadium', 'lastUpdated': '2022-02-10T19:48:56Z'}}, {'id': 272, 'startDate': '2000-08-19', 'endDate': '2001-05-19', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 273, 'startDate': '1999-08-07', 'endDate': '2000-05-14', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 274, 'startDate': '1998-08-15', 'endDate': '1999-05-16', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 275, 'startDate': '1997-08-09', 'endDate': '1998-05-10', 'currentMatchday': None, 'winner': {'id': 57, 'name': 'Arsenal FC', 'shortName': 'Arsenal', 'tla': 'ARS', 'crest': 'https://crests.football-data.org/57.png', 'address': '75 Drayton Park London N5 1BU', 'website': 'http://www.arsenal.com', 'founded': 1886, 'clubColors': 'Red / White', 'venue': 'Emirates Stadium', 'lastUpdated': '2022-02-10T19:48:56Z'}}, {'id': 276, 'startDate': '1996-08-17', 'endDate': '1997-05-11', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 277, 'startDate': '1995-08-19', 'endDate': '1996-05-04', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 254, 'startDate': '1994-08-20', 'endDate': '1995-05-14', 'currentMatchday': None, 'winner': {'id': 59, 'name': 'Blackburn Rovers FC', 'shortName': 'Blackburn', 'tla': 'BLA', 'crest': 'https://crests.football-data.org/59.png', 'address': 'Ewood Park Blackburn BB2 4JF', 'website': 'http://www.rovers.co.uk', 'founded': 1874, 'clubColors': 'Blue / White', 'venue': 'Ewood Park', 'lastUpdated': '2022-02-19T08:50:27Z'}}, {'id': 255, 'startDate': '1993-08-14', 'endDate': '1994-05-08', 'currentMatchday': None, 'winner': {'id': 66, 'name': 'Manchester United FC', 'shortName': 'Man United', 'tla': 'MUN', 'crest': 'https://crests.football-data.org/66.png', 'address': 'Sir Matt Busby Way Manchester M16 0RA', 'website': 'http://www.manutd.com', 'founded': 1878, 'clubColors': 'Red / White', 'venue': 'Old Trafford', 'lastUpdated': '2022-02-10T19:27:46Z'}}, {'id': 818, 'startDate': '1992-08-13', 'endDate': '1993-05-09', 'currentMatchday': None, 'winner': None}, {'id': 819, 'startDate': '1991-08-15', 'endDate': '1992-04-30', 'currentMatchday': None, 'winner': None}, {'id': 820, 'startDate': '1990-08-23', 'endDate': '1991-05-18', 'currentMatchday': None, 'winner': None}, {'id': 821, 'startDate': '1989-08-17', 'endDate': '1990-05-03', 'currentMatchday': None, 'winner': None}, {'id': 822, 'startDate': '1988-08-25', 'endDate': '1989-05-24', 'currentMatchday': None, 'winner': None}, {'id': 913, 'startDate': '1987-08-13', 'endDate': '1988-05-13', 'currentMatchday': None, 'winner': None}, {'id': 823, 'startDate': '1986-08-21', 'endDate': '1987-05-09', 'currentMatchday': None, 'winner': None}, {'id': 824, 'startDate': '1985-08-15', 'endDate': '1986-05-03', 'currentMatchday': None, 'winner': None}, {'id': 825, 'startDate': '1984-08-23', 'endDate': '1985-05-26', 'currentMatchday': None, 'winner': None}, {'id': 826, 'startDate': '1983-08-25', 'endDate': '1984-05-15', 'currentMatchday': None, 'winner': None}, {'id': 827, 'startDate': '1982-08-26', 'endDate': '1983-05-12', 'currentMatchday': None, 'winner': None}, {'id': 828, 'startDate': '1981-08-27', 'endDate': '1982-05-19', 'currentMatchday': None, 'winner': None}, {'id': 829, 'startDate': '1980-08-14', 'endDate': '1981-05-17', 'currentMatchday': None, 'winner': None}, {'id': 830, 'startDate': '1979-08-16', 'endDate': '1980-05-17', 'currentMatchday': None, 'winner': None}, {'id': 831, 'startDate': '1978-08-17', 'endDate': '1979-05-16', 'currentMatchday': None, 'winner': None}, {'id': 832, 'startDate': '1977-08-18', 'endDate': '1978-05-07', 'currentMatchday': None, 'winner': None}, {'id': 833, 'startDate': '1976-08-19', 'endDate': '1977-05-22', 'currentMatchday': None, 'winner': None}, {'id': 834, 'startDate': '1975-08-14', 'endDate': '1976-05-02', 'currentMatchday': None, 'winner': None}, {'id': 835, 'startDate': '1974-08-15', 'endDate': '1975-04-27', 'currentMatchday': None, 'winner': None}, {'id': 836, 'startDate': '1973-08-23', 'endDate': '1974-05-09', 'currentMatchday': None, 'winner': None}, {'id': 837, 'startDate': '1972-08-10', 'endDate': '1973-05-07', 'currentMatchday': None, 'winner': None}, {'id': 838, 'startDate': '1971-08-12', 'endDate': '1972-05-09', 'currentMatchday': None, 'winner': None}, {'id': 912, 'startDate': '1970-08-13', 'endDate': '1971-05-03', 'currentMatchday': None, 'winner': None}, {'id': 839, 'startDate': '1969-08-07', 'endDate': '1970-04-30', 'currentMatchday': None, 'winner': None}, {'id': 914, 'startDate': '1968-08-08', 'endDate': '1969-05-15', 'currentMatchday': None, 'winner': None}, {'id': 915, 'startDate': '1967-08-17', 'endDate': '1968-05-19', 'currentMatchday': None, 'winner': None}, {'id': 916, 'startDate': '1966-08-18', 'endDate': '1967-05-14', 'currentMatchday': None, 'winner': None}, {'id': 925, 'startDate': '1965-08-19', 'endDate': '1966-05-17', 'currentMatchday': None, 'winner': None}, {'id': 924, 'startDate': '1964-08-20', 'endDate': '1965-04-26', 'currentMatchday': None, 'winner': None}, {'id': 923, 'startDate': '1963-08-22', 'endDate': '1964-04-27', 'currentMatchday': None, 'winner': None}, {'id': 922, 'startDate': '1962-08-16', 'endDate': '1963-05-19', 'currentMatchday': None, 'winner': None}, {'id': 921, 'startDate': '1961-08-17', 'endDate': '1962-04-29', 'currentMatchday': None, 'winner': None}, {'id': 920, 'startDate': '1960-08-18', 'endDate': '1961-04-27', 'currentMatchday': None, 'winner': None}, {'id': 919, 'startDate': '1959-08-20', 'endDate': '1960-04-30', 'currentMatchday': None, 'winner': None}, {'id': 918, 'startDate': '1958-08-21', 'endDate': '1959-05-02', 'currentMatchday': None, 'winner': None}, {'id': 917, 'startDate': '1957-08-22', 'endDate': '1958-04-28', 'currentMatchday': None, 'winner': None}, {'id': 926, 'startDate': '1956-08-16', 'endDate': '1957-04-29', 'currentMatchday': None, 'winner': None}, {'id': 935, 'startDate': '1955-08-18', 'endDate': '1956-04-30', 'currentMatchday': None, 'winner': None}, {'id': 936, 'startDate': '1954-08-19', 'endDate': '1955-05-03', 'currentMatchday': None, 'winner': None}, {'id': 937, 'startDate': '1953-08-17', 'endDate': '1954-04-24', 'currentMatchday': None, 'winner': None}, {'id': 938, 'startDate': '1952-08-21', 'endDate': '1953-04-30', 'currentMatchday': None, 'winner': None}, {'id': 939, 'startDate': '1951-08-16', 'endDate': '1952-05-01', 'currentMatchday': None, 'winner': None}, {'id': 940, 'startDate': '1950-08-17', 'endDate': '1951-05-03', 'currentMatchday': None, 'winner': None}, {'id': 934, 'startDate': '1949-08-18', 'endDate': '1950-05-04', 'currentMatchday': None, 'winner': None}, {'id': 933, 'startDate': '1948-08-19', 'endDate': '1949-05-07', 'currentMatchday': None, 'winner': None}, {'id': 932, 'startDate': '1947-08-21', 'endDate': '1948-04-29', 'currentMatchday': None, 'winner': None}, {'id': 931, 'startDate': '1946-08-29', 'endDate': '1947-06-12', 'currentMatchday': None, 'winner': None}, {'id': 930, 'startDate': '1938-08-25', 'endDate': '1939-05-04', 'currentMatchday': None, 'winner': None}, {'id': 928, 'startDate': '1937-08-26', 'endDate': '1938-05-05', 'currentMatchday': None, 'winner': None}, {'id': 927, 'startDate': '1936-08-27', 'endDate': '1937-04-29', 'currentMatchday': None, 'winner': None}, {'id': 929, 'startDate': '1935-08-29', 'endDate': '1936-04-30', 'currentMatchday': None, 'winner': None}, {'id': 963, 'startDate': '1934-08-23', 'endDate': '1935-05-02', 'currentMatchday': None, 'winner': None}, {'id': 950, 'startDate': '1933-08-24', 'endDate': '1934-05-03', 'currentMatchday': None, 'winner': None}, {'id': 949, 'startDate': '1932-08-25', 'endDate': '1933-05-04', 'currentMatchday': None, 'winner': None}, {'id': 948, 'startDate': '1931-08-27', 'endDate': '1932-05-05', 'currentMatchday': None, 'winner': None}, {'id': 947, 'startDate': '1930-08-28', 'endDate': '1931-04-30', 'currentMatchday': None, 'winner': None}, {'id': 946, 'startDate': '1929-08-29', 'endDate': '1930-05-01', 'currentMatchday': None, 'winner': None}, {'id': 945, 'startDate': '1928-08-23', 'endDate': '1929-05-02', 'currentMatchday': None, 'winner': None}, {'id': 944, 'startDate': '1927-08-25', 'endDate': '1928-05-03', 'currentMatchday': None, 'winner': None}, {'id': 943, 'startDate': '1926-08-26', 'endDate': '1927-05-05', 'currentMatchday': None, 'winner': None}, {'id': 942, 'startDate': '1925-08-27', 'endDate': '1926-04-29', 'currentMatchday': None, 'winner': None}, {'id': 941, 'startDate': '1924-08-28', 'endDate': '1925-04-30', 'currentMatchday': None, 'winner': None}, {'id': 951, 'startDate': '1923-08-23', 'endDate': '1924-05-01', 'currentMatchday': None, 'winner': None}, {'id': 952, 'startDate': '1922-08-24', 'endDate': '1923-05-03', 'currentMatchday': None, 'winner': None}, {'id': 962, 'startDate': '1921-08-25', 'endDate': '1922-05-04', 'currentMatchday': None, 'winner': None}, {'id': 961, 'startDate': '1920-08-26', 'endDate': '1921-05-05', 'currentMatchday': None, 'winner': None}, {'id': 960, 'startDate': '1919-08-28', 'endDate': '1920-04-29', 'currentMatchday': None, 'winner': None}, {'id': 957, 'startDate': '1914-08-30', 'endDate': '1915-04-26', 'currentMatchday': None, 'winner': None}, {'id': 958, 'startDate': '1913-08-30', 'endDate': '1914-04-25', 'currentMatchday': None, 'winner': None}, {'id': 955, 'startDate': '1912-08-31', 'endDate': '1913-04-28', 'c

In [1]:
# postman 시도하기

### Betting Data

 - 배당률을 따로 DB에 쌓지 않기로 결정, 바로 가공하는 과정이 필요하다.
 - 추후 조합픽도 한번에 돌릴 수 있도록 하기 위해 노말부터 모두 가져온다.

In [5]:
# AWS lsports 배당률 데이터 연결, 불러오기
## Bet365 provider_id = 8

db_connection_str = '-'
db_connection = create_engine(db_connection_str)

bet1 = pd.read_sql('''
                    SELECT fixture.league_id, fixture.start_date, home.name as home_name, away.name as away_name, bet.provider_id, provider.name, market_id, bet.name as wdl, bet.price, bet.base_line, status
                    FROM lsports_shadow.fixture
                    JOIN lsports_shadow.participant AS home on fixture.home_id = home.id
                    JOIN lsports_shadow.participant AS away on fixture.away_id = away.id
                    JOIN lsports_shadow.bet on fixture.id = bet.fixture_id
                    JOIN lsports.provider on bet.provider_id = provider.id
                    WHERE (league_id = 8910 AND league_id = 895 or league_id = 94 or league_id = 123 or league_id = 207  
                    or league_id = 99 or league_id = 199 ) AND bet.market_id = '1_1'AND provider_id = 8

                    ''', \
                     con=db_connection)

bet2 = pd.read_sql('''
                    SELECT fixture.league_id, fixture.start_date, home.name as home_name, away.name as away_name, bet.provider_id, provider.name, market_id, bet.name as wdl, bet.price, bet.base_line, status
                    FROM lsports_shadow.fixture
                    JOIN lsports_shadow.participant AS home on fixture.home_id = home.id
                    JOIN lsports_shadow.participant AS away on fixture.away_id = away.id
                    JOIN lsports_shadow.bet on fixture.id = bet.fixture_id
                    JOIN lsports.provider on bet.provider_id = provider.id
                    WHERE (league_id = 8910 AND league_id = 895 or league_id = 94 or league_id = 123 or league_id = 207  
                    or league_id = 99 or league_id = 199 ) AND bet.market_id = '1_2'AND provider_id = 8

                    ''', \
                     con=db_connection)

bet3 = pd.read_sql('''
                    SELECT fixture.league_id, fixture.start_date, home.name as home_name, away.name as away_name, 
                    bet.provider_id, provider.name, market_id, bet.name as wdl, bet.price, bet.base_line, status
                    FROM lsports_shadow.fixture
                    JOIN lsports_shadow.participant AS home on fixture.home_id = home.id
                    JOIN lsports_shadow.participant AS away on fixture.away_id = away.id
                    JOIN lsports_shadow.bet on fixture.id = bet.fixture_id
                    JOIN lsports.provider on bet.provider_id = provider.id
                    WHERE (league_id = 8910 AND league_id = 895 or league_id = 94 or league_id = 123 or league_id = 207  
                    or league_id = 99 or league_id = 199 ) AND bet.market_id = '1_3'AND provider_id = 8

                    ''', \
                     con=db_connection)

## 데이터 프레임 형태로 배당률 정리
## 일반 승무패 배당률. market_id = 1_1

def bet_norm(data):

    data = pd.DataFrame(data.groupby(['start_date','league_id', 'home_name', 'away_name', 'wdl','status']).mean()['price'].reset_index())
    temp = data.values.tolist()

    dataTemp = []
    row = {}
    for i in range(0,len(temp)):
        if i % 3 == 0:
            row = {}
            row['date'] = temp[i][0]
            row['league_id'] = temp[i][1]
            row['home'] = temp[i][2]
            row['away'] = temp[i][3]
            row['status'] = temp[i][5]
            row['home_odd'] = temp[i][6]
        elif i % 3 == 1:
            row['away_odd'] = temp[i][6]
        elif i % 3 == 2:
            row['draw_odd'] = temp[i][6]
            dataTemp.append(row)

    bet_1 = pd.DataFrame(dataTemp)

    bet_1['date'] = bet_1['date'].dt.date

    bet_1 = bet_1.reset_index()
    bet_1 = bet_1.drop('index',axis=1)
    
    bet_1.insert(2,'league','')
    
    for i in range(0,len(bet_1)):
        if bet_1['league_id'][i] == 8910:
            bet_1['league'][i] = 'K League 1'
        elif bet_1['league_id'][i] == 895:
            bet_1['league'][i] = 'J1 League'
        elif bet_1['league_id'][i] == 849:
            bet_1['league'][i] = 'CSL'
        elif bet_1['league_id'][i] == 94:
            bet_1['league'][i] = 'England Premire League'
        elif bet_1['league_id'][i] == 123:
            bet_1['league'][i] = 'Bundesliga'
        elif bet_1['league_id'][i] == 207:
            bet_1['league'][i] = 'Primera Division'
        elif bet_1['league_id'][i] == 99:
            bet_1['league'][i] = 'League 1'
        elif bet_1['league_id'][i] == 199:
            bet_1['league'][i] = 'Serie A'
    
    bet_1.dropna().reset_index().drop('index',axis=1)
    
    return bet_1

## 핸디캡 배당률. market_id = 1_2

def bet_handi(data):
#     data = pd.DataFrame(data.groupby(['start_date','league_id', 'home_name', 'away_name','name', 'base_line','status']).mean()['price'].reset_index())
    temp = data.values.tolist()
#     return temp

    dataTemp = []
    row = {}

    for i in range(0,len(temp)):
        if i % 2 == 0:
            row = {}
            row['date'] = temp[i][1]
            row['league_id'] = temp[i][0]
            row['home'] = temp[i][2]
            row['away'] = temp[i][3]
            row['provider'] = temp[i][5]
            row['base_line'] = temp[i][9]
            row['status'] = temp[i][10]
            row['home_odd'] = temp[i][8]
        elif i % 2 == 1:
            row['away_odd'] = temp[i][8]
            dataTemp.append(row)
            
    bet_2 = pd.DataFrame(dataTemp)

    import datetime as dt
    bet_2['date'] = bet_2['date'].dt.date

    bet_2 = bet_2.reset_index()
    bet_2 = bet_2.drop('index',axis=1)

    bet_2 = bet_2.sort_values(by=['date','home'])
    bet_2 = bet_2.reset_index()
    bet_2 = bet_2.drop(['index'],axis=1)
    

    bet_2.insert(2,'league','')
    
    for i in range(0,len(bet_2)):
        if bet_2['league_id'][i] == 8910:
            bet_2['league'][i] = 'K League 1'
        elif bet_2['league_id'][i] == 895:
            bet_2['league'][i] = 'J1 League'
        elif bet_2['league_id'][i] == 849:
            bet_2['league'][i] = 'CSL'
        elif bet_2['league_id'][i] == 94:
            bet_2['league'][i] = 'England Premire League'
        elif bet_2['league_id'][i] == 123:
            bet_2['league'][i] = 'Bundesliga'
        elif bet_2['league_id'][i] == 207:
            bet_2['league'][i] = 'Primera Division'
        elif bet_2['league_id'][i] == 99:
            bet_2['league'][i] = 'League 1'
        elif bet_2['league_id'][i] == 199:
            bet_2['league'][i] = 'Serie A'
            
            
    return bet_2

## 언더오버 배당률. market_id = 1_3

def bet_unov(data):
    data.columns = ['league_id','start_date','home_name','away_name','provider_id','provider_name','market_id','wdl','price','base_line','status']

# 배당률 이상치 보정
#     for i in range(0,len(data)):
#         if data['price'][i] > 15:
#             data['price'][i] = 15

#     data = pd.DataFrame(data.groupby(['start_date','league_id', 'home_name', 'away_name','provider_name', 'base_line','status']).mean()['price'].reset_index())

    temp = data.values.tolist()

    dataTemp = []
    row = {}

    for i in range(0,len(temp)):
        if i % 2 == 0:
            row = {}
            row['date'] = temp[i][1]
            row['league_id'] = temp[i][0]
            row['home'] = temp[i][2]
            row['away'] = temp[i][3]
            row['provider'] = temp[i][5]
            row['base_line'] = temp[i][9]
            row['status'] = temp[i][10]
            row['over_odd'] = temp[i][8]
        elif i % 2 == 1:
            row['under_odd'] = temp[i][8]
            dataTemp.append(row)

    bet_3 = pd.DataFrame(dataTemp)

    bet_3['date'] = bet_3['date'].dt.date

    bet_3 = bet_3.reset_index()
    bet_3 = bet_3.drop('index',axis=1)

    bet_3 = bet_3.sort_values(by=['date','home'])
    bet_3 = bet_3.reset_index()
    bet_3 = bet_3.drop(['index'],axis=1)
    
    bet_3.insert(2,'league','')
    
    for i in range(0,len(bet_3)):
        if bet_3['league_id'][i] == 8910:
            bet_3['league'][i] = 'K League 1'
        elif bet_3['league_id'][i] == 895:
            bet_3['league'][i] = 'J1 League'
        elif bet_3['league_id'][i] == 849:
            bet_3['league'][i] = 'CSL'
        elif bet_3['league_id'][i] == 94:
            bet_3['league'][i] = 'England Premire League'
        elif bet_3['league_id'][i] == 123:
            bet_3['league'][i] = 'Bundesliga'
        elif bet_3['league_id'][i] == 207:
            bet_3['league'][i] = 'Primera Division'
        elif bet_3['league_id'][i] == 99:
            bet_3['league'][i] = 'League 1'
        elif bet_3['league_id'][i] == 199:
            bet_3['league'][i] = 'Serie A'
    
    return bet_3

norm = bet_norm(bet1)
handi = bet_handi(bet2)
unov = bet_unov(bet3)
        
# 배당률 데이터와 와이스카웃 이름 다른 문제 해결
    
## 노말 이름 바꾸기
norm = norm.replace('Yokohama F-Marinos', 'Yokohama F. Marinos')

norm = norm.replace('Daegu FC', 'Daegu').replace('Seongnam FC', 'Seongnam').replace('Gwangju FC', 'Gwangju').replace('Incheon Utd', 'Incheon United')\
.replace('Gangwon FC', 'Gangwon').replace('FC Seoul', 'Seoul').replace('Suwon FC', 'Suwon')

norm = norm.replace('Tottenham', 'Tottenham Hotspur').replace('Man Utd', 'Manchester United').replace('Brighton', 'Brighton & Hove Albion')\
.replace('Leicester', 'Leicester City').replace('Newcastle', 'Newcastle United').replace('Bournemouth', 'AFC Bournemouth').replace('West Ham', 'West Ham United')\
.replace('Sheff Utd', 'Sheffield United').replace('West Brom', 'West Bromwich Albion').replace('Leeds', 'Leeds United').replace('Man City', 'Manchester City')

norm = norm.replace('Angers', 'Angers SCO').replace('Marseille', 'Olympique Marseille').replace('Nimes', 'Nîmes').replace('Amiens', 'Amiens SC')\
.replace('St Etienne', 'Saint-Étienne').replace('Lyon', 'Olympique Lyonnais')

norm = norm.replace('Mainz', 'Mainz 05').replace('SC Freiburg', 'Freiburg').replace('Schalke', 'Schalke 04').replace('Bayern Munich', 'Bayern München')\
.replace('TSG Hoffenheim', 'Hoffenheim').replace('VfB Stuttgart', 'Stuttgart').replace('Cologne', 'Köln')

norm = norm.replace('Inter Milan', 'Internazionale').replace('AC Milan', 'Milan').replace('Verona', 'Hellas Verona').replace('Spal', 'SPAL')

norm = norm.replace('Celta Vigo', 'Celta de Vigo').replace('Valladolid', 'Real Valladolid')


## 핸디캡 이름 바꾸기
handi = handi.replace('Yokohama F-Marinos', 'Yokohama F. Marinos')

handi = handi.replace('Daegu FC', 'Daegu').replace('Seongnam FC', 'Seongnam').replace('Gwangju FC', 'Gwangju').replace('Incheon Utd', 'Incheon United')\
.replace('Gangwon FC', 'Gangwon').replace('FC Seoul', 'Seoul').replace('Suwon FC', 'Suwon')

handi = handi.replace('Tottenham', 'Tottenham Hotspur').replace('Man Utd', 'Manchester United').replace('Brighton', 'Brighton & Hove Albion')\
.replace('Leicester', 'Leicester City').replace('Newcastle', 'Newcastle United').replace('Bournemouth', 'AFC Bournemouth').replace('West Ham', 'West Ham United')\
.replace('Sheff Utd', 'Sheffield United').replace('West Brom', 'West Bromwich Albion').replace('Leeds', 'Leeds United').replace('Man City', 'Manchester City')

handi = handi.replace('Angers', 'Angers SCO').replace('Marseille', 'Olympique Marseille').replace('Nimes', 'Nîmes').replace('Amiens', 'Amiens SC')\
.replace('St Etienne', 'Saint-Étienne').replace('Lyon', 'Olympique Lyonnais')

handi = handi.replace('Mainz', 'Mainz 05').replace('SC Freiburg', 'Freiburg').replace('Schalke', 'Schalke 04').replace('Bayern Munich', 'Bayern München')\
.replace('TSG Hoffenheim', 'Hoffenheim').replace('VfB Stuttgart', 'Stuttgart').replace('Cologne', 'Köln')

handi = handi.replace('Inter Milan', 'Internazionale').replace('AC Milan', 'Milan').replace('Verona', 'Hellas Verona').replace('Spal', 'SPAL')

handi = handi.replace('Celta Vigo', 'Celta de Vigo').replace('Valladolid', 'Real Valladolid')

# handi['date'] = pd.to_datetime(handi['date'],format='%Y-%M-%d')
handi = handi[['date','league_id','league','home','away','base_line','home_odd','away_odd']]

## 전체 다 소문자로 바꾸기
for i in range(0,len(handi)):
    handi['home'][i] = handi['home'][i].lower()
    handi['away'][i] = handi['away'][i].lower() 

## 언더오버 이름 바꾸기
unov = unov.replace('Yokohama F-Marinos', 'Yokohama F. Marinos')

unov = unov.replace('Daegu FC', 'Daegu').replace('Seongnam FC', 'Seongnam').replace('Gwangju FC', 'Gwangju').replace('Incheon Utd', 'Incheon United')\
.replace('Gangwon FC', 'Gangwon').replace('FC Seoul', 'Seoul').replace('Suwon FC', 'Suwon')

unov = unov.replace('Tottenham', 'Tottenham Hotspur').replace('Man Utd', 'Manchester United').replace('Brighton', 'Brighton & Hove Albion')\
.replace('Leicester', 'Leicester City').replace('Newcastle', 'Newcastle United').replace('Bournemouth', 'AFC Bournemouth').replace('West Ham', 'West Ham United')\
.replace('Sheff Utd', 'Sheffield United').replace('West Brom', 'West Bromwich Albion').replace('Leeds', 'Leeds United').replace('Man City', 'Manchester City')

unov = unov.replace('Angers', 'Angers SCO').replace('Marseille', 'Olympique Marseille').replace('Nimes', 'Nîmes').replace('Amiens', 'Amiens SC')\
.replace('St Etienne', 'Saint-Étienne').replace('Lyon', 'Olympique Lyonnais')

unov = unov.replace('Mainz', 'Mainz 05').replace('SC Freiburg', 'Freiburg').replace('Schalke', 'Schalke 04').replace('Bayern Munich', 'Bayern München')\
.replace('TSG Hoffenheim', 'Hoffenheim').replace('VfB Stuttgart', 'Stuttgart').replace('Cologne', 'Köln')

unov = unov.replace('Inter Milan', 'Internazionale').replace('AC Milan', 'Milan').replace('Verona', 'Hellas Verona').replace('Spal', 'SPAL')

unov = unov.replace('Celta Vigo', 'Celta de Vigo').replace('Valladolid', 'Real Valladolid')

# unov['date'] = pd.to_datetime(unov['date'],format='%Y-%M-%d')
# unov = unov[['date','league_id','league','home','away','base_line','under_odd','away_odd']]

## 전체 다 소문자로 바꾸기
for i in range(0,len(unov)):
    unov['home'][i] = unov['home'][i].lower()
    unov['away'][i] = unov['away'][i].lower()

## Making Functions

 - make_train(raw_data) : 학습데이터 만드는 함수(raw_data : selection 필터링 된 raw데이터)
 - make_test(data,raw_data) : 테스트 데이터 만드는 함수(data : fixture데이터, raw_data : selection 필터링 된 raw데이터)

In [14]:
# 테스트 데이터 만드는 함수 설정

def make_test(raw1,raw2):
    
    data = raw1.copy()
    # 7대리그만 필터링
    data.query("competition_id == [551,534,287,364,412,426,524,795]",True)
    data = data.reset_index().drop('index',axis=1)

    fix = data.copy()
    # return fix

    # 월/목만 돌아가도록
    if dt.datetime.now().strftime('%a') == 'Mon':
        fix = fix[(fix['date'] >= dt.datetime.now()) & (fix['date'] <= (dt.datetime.now() + timedelta(days=3)))]
        fix = fix.sort_values(by=['competition_id']).reset_index().drop('index',axis=1)

    elif dt.datetime.now().strftime('%a') == 'Thu':
        fix = fix[(fix['date'] >= dt.datetime.now()) & (fix['date'] <= (dt.datetime.now() + timedelta(days=4)))]
        fix = fix.sort_values(by=['competition_id']).reset_index().drop('index',axis=1)

    else:
        fix = fix[(fix['date'] >= (dt.datetime.now() - timedelta(days=1))) & (fix['date'] <= (dt.datetime.now() + timedelta(days=3)))]
        fix = fix.sort_values(by=['competition_id']).reset_index().drop('index',axis=1)

    ## 특정 기간만 돌릴 때
    # fix = fix[(fix['date'] >= dt.datetime.strptime('2021-08-23 09:00:00', '%Y-%m-%d %H:%M:%S')) &
    #           (fix['date'] <= dt.datetime.strptime('2021-08-26 09:00:00', '%Y-%m-%d %H:%M:%S'))].reset_index().drop('index',axis=1)

    test = fix.copy()

    j = len(test.columns)

    # 10가지 컬럼 선정
    cols = ['team_id','match_id','possession_percent','xg','goals','progressive_runs','touches_in_box','shots_on_target',
           'through_passes_successful','pass_to_final_thirds_successful','tackles','ppda']
    mean = raw2.groupby('team_id').mean().reset_index()[cols]

    # 평균값으로 넣기
    for i in mean.columns[2:]:
        test.insert(j,'away_{}'.format(i),0.000)

    for k in mean.columns[2:]:
        test.insert(j,'home_{}'.format(k),0.000)

    for i in range(0,len(test)):
        for e in mean.columns[2:]:
            test['away_{}'.format(e)][i] = mean[mean['team_id'] == test['away_id'][i]]['{}'.format(e)].values[0]
            test['home_{}'.format(e)][i] = mean[mean['team_id'] == test['home_id'][i]]['{}'.format(e)].values[0]

    return test

# 일반 승무패 파이캐럿 돌리는 함수 
def py_norm(train,test):
    
    # 에러 대비해서 try-except문 활용
    try:
        setup_clf = setup(data = train[input_var_h], target = 'home_result_pts', silent = True,normalize = True, normalize_method = 'robust')
        comp = compare_models(sort='F1',n_select=1)
        tune = tune_model(comp,optimize='F1')
        pred = predict_model(tune,data=test,raw_score=True)
#         return pred

        a = pred[['matche_id','competition_id','season_id','date','home_id','away_id','Label','Score_0','Score_1','Score_3']]
        a.columns = ['match_id','competition_id','season_id','date','home_id','away_id','label','score_lose','score_draw','score_win']
        a['label'] = a['label'].astype('float64')

        a.insert(7,'category', 'normal')
        a.insert(8,'base_line',0)
    
        # 모델 이름 두가지 경우로 나눠서 넣기
        try:
            a.insert(9,'model_name',str(tune).split('<')[1].split('.')[0])
        except IndexError as err:
            a.insert(9,'model_name',str(tune).split('(')[0])
#         return a
        
        # 회사 서버 footballer에 쌓기
        # AWS allstat_service 생기면 이전
        engine = create_engine("mysql+mysqldb://admin:"+"irAEllwx8rAj62riARVeBTJ3"+"@wyscout.cb9e9sl9n5hy.ap-northeast-2.rds.amazonaws.com:3306/allstat", encoding='utf-8')
        conn = engine.connect()

        return a.to_sql(name='model', con=engine, if_exists='append', index=False)

    except ValueError as err:
        print(err)
#             pass


# 핸디캡 파이캐럿 돌리는 함수
def py_handi(train,test,handi_mean):
    
    try:
    #     ------------------------------------------
    #   배당률 데이터에서 base_line 가져오기
        test1 = test.copy()

        for i in range(0,len(test1)):
            test1['date'][i] = test1['date'][i].strftime('%Y-%m-%d')
            test1['home_name'][i] = test1['home_name'][i].lower()
            test1['away_name'][i] = test1['away_name'][i].lower()

        test1 = test1.rename(columns={'home_name' : 'home'})
        test1 = test1.rename(columns={'away_name' : 'away'})
    #     return test1

        handi_mean['date'] = pd.to_datetime(handi_mean['date'])
    #     return handi_mean

        fix_bet = pd.merge(handi_mean[['date','home','away','base_line','home_odd','away_odd']],test1,on = ['date','home','away'])
    #     return fix_bet

        test_1 = pd.merge(fix_bet[['base_line','home_odd','away_odd','matche_id']],test,on='matche_id')
        
    # 해외업체 평균으로 계산할 경우
    # 현재는 bet365 만 사용중이므로 사용 X
#         test_1.insert(10,'base_line',0)
        
#         for i in range(0,len(test_1)):
#             if test_1['home_odd'][i] > test_1['away_odd'][i]:
#                 test_1['base_line'][i] = 1
#             elif test_1['home_odd'][i] < test_1['away_odd'][i]:
#                 test_1['base_line'][i] = -1
#             elif test_1['home_odd'][i] == test_1['away_odd'][i]:
#                 if test_1['baseline'][i] > 0:
#                     test_1['base_line'][i] = 1
#                 elif test_1['baseline'][i] < 0:
#                     test_1['base_line'][i] = -1

        test_1['home_goals'] = test_1['home_goals'] + test_1['base_line']
    #    return test_1

        test_2 = test_1.copy()
    #     ------------------------------------------
        setup_clf = setup(data = train[input_var_h], target = 'home_result_pts', silent = True,normalize = True, normalize_method = 'robust')
        comp = compare_models(sort='Accuracy',n_select=1)
        tune = tune_model(comp,optimize='Accuracy')
        pred = predict_model(tune,data=test_2,raw_score=True)
    #     return pred

        a = pred[['matche_id','competition_id','season_id','date','home_id','away_id','base_line','Label','Score_0','Score_1','Score_3']]
        a.columns = ['match_id','competition_id','season_id','date','home_id','away_id','base_line','label','score_lose','score_draw','score_win']
        a['label'] = a['label'].astype('float64')

        a.insert(6,'category','handicap')

        try:
            a.insert(9,'model_name',str(tune).split('<')[1].split('.')[0])
        except IndexError as err:
            a.insert(9,'model_name',str(tune).split('(')[0])
            
#         return a
            
        engine = create_engine("mysql+mysqldb://admin:"+"irAEllwx8rAj62riARVeBTJ3"+"@wyscout.cb9e9sl9n5hy.ap-northeast-2.rds.amazonaws.com:3306/allstat", encoding='utf-8')
        conn = engine.connect()

        return a.to_sql(name='model', con=engine, if_exists='append', index=False)
    
    except ValueError as err:
        print(err)
#         pass
    
# #----------------------------------------------------------------    

def py_unov(train, test, unov_mean):
    
    try:
    #     ------------------------------------------
    #   배당률 데이터에서 base_line 가져오기
        test1 = test.copy()
        for i in range(0,len(test1)):
            test1['date'][i] = test1['date'][i].strftime('%Y-%m-%d')
            test1['home_name'][i] = test1['home_name'][i].lower()
            test1['away_name'][i] = test1['away_name'][i].lower()

        test1 = test1.rename(columns={'home_name' : 'home'})
        test1 = test1.rename(columns={'away_name' : 'away'})

       
        unov_mean['date'] = pd.to_datetime(unov_mean['date'])

        fix_bet = pd.merge(unov_mean[['date','home','away','base_line']], test1, on = ['date','home','away'])

        #------------------------------------------

        test_1 = pd.merge(fix_bet[['base_line','matche_id']],test,on='matche_id')
#         test_1.insert(10,'base_line',0)
        
#         for i in range(0,len(test_1)):
#             if test_1['baseline'][i] <= 1.75:
#                 test_1['base_line'][i] = 1.5
#             elif (1.75 < test_1['baseline'][i]) & (test_1['baseline'][i] <= 2.25):
#                 test_1['base_line'][i] = 2.0
#             elif (2.25 < test_1['baseline'][i]) & (test_1['baseline'][i] <= 2.75):
#                 test_1['base_line'][i] = 2.5
#             elif (2.75 < test_1['baseline'][i]) & (test_1['baseline'][i] <= 3.25):
#                 test_1['base_line'][i] = 3.0
#             elif (3.25 < test_1['baseline'][i]) & (test_1['baseline'][i] <= 3.75):
#                 test_1['base_line'][i] = 3.5
#             elif 3.75 < test_1['baseline'][i]:
#                 test_1['base_line'][i] = 4.0

        test_2 = test_1.copy()

        train_1 = train.copy()
        train_1['goals'] = train_1['home_goals'] + train_1['away_goals']
    #     ------------------------------------------
        setup_reg = setup(data = train_1[input_var_g], target = 'goals', silent=True)
        comp = compare_models(sort='MSE',n_select=1)
        tune = tune_model(comp,optimize='MSE')
        pred = predict_model(tune, data = test_2)
    #     return pred

        a = pred[['matche_id','competition_id','season_id','date','home_id','away_id','base_line','Label']]
        a.columns = ['match_id','competition_id','season_id','date','home_id','away_id','base_line','label']
        a.insert(6,'category','under over')

        a['label'] = a['label'].astype('float64')
                
#         for i in range(len(a)):
#             if a['label'][i] > a['base_line'][i]:
#                 a['label'][i] = 'over'
#             elif a['label'][i] < a['base_line'][i]:
#                 a['label'][i] = 'under'
#             else:
#                 pass
        
    # 언더오버는 확률이 없기 때문에 같은 테이블에 넣기 위해 컬럼 만들어줌
        a.insert(9,'score_lose',0)
        a.insert(10,'score_draw',0)
        a.insert(11,'score_win',0)
        
        try:
            a.insert(9,'model_name',str(tune).split('<')[1].split('.')[0])
        except IndexError as err:
            a.insert(9,'model_name',str(tune).split('(')[0])
            
#         return a
        
        engine = create_engine("mysql+mysqldb://admin:"+"irAEllwx8rAj62riARVeBTJ3"+"@wyscout.cb9e9sl9n5hy.ap-northeast-2.rds.amazonaws.com:3306/allstat", encoding='utf-8')
        conn = engine.connect()

        return a.to_sql(name='model', con=engine, if_exists='append', index=False)
    
    except ValueError as err:
        print(err)
#         pass

In [15]:
# handi
# py_handi(train_list[0],test_list[0],handi)

## Making Data

In [16]:
# 데이터 생성하기
# pd.set_option('display.max_columns',100)

## 학습데이터
## 홈 승점, 결과 라벨만 붙여서 raw_dt 그대로 사용
data = raw_dt.copy()

data.insert(10,'result','')
data.insert(11,'home_result_pts',0)

for i in range(0,len(data)):

    if data['winner'][i] == data['home_id'][i]:
        data['result'][i] = 'HW'
        data['home_result_pts'][i] = 3
        
    elif data['winner'][i] == data['away_id'][i]:
        data['result'][i] = 'AW'
        data['home_result_pts'][i] = 0
        
    elif data['winner'][i] == 0:
        data['result'][i] = 'DR'
        data['home_result_pts'][i] = 1
        
# data.head()

train = data.copy()

## 테스트 데이터는 앞에서 만든 함수 활용
test = make_test(raw_if,raw_pa)

## 리그별로 나누기
gb_train = train.groupby('competition_id') 
gb_test = test.groupby('competition_id')

train_list = []
test_list = []

for x in gb_test.groups:
    a = gb_train.get_group(x).reset_index().drop('index',axis=1)
    train_list.append(a)
    
    b = gb_test.get_group(x).reset_index().drop('index',axis=1)
    test_list.append(b)

# test_list[0]

In [17]:

# train.insert(17,'home_h2h',0)
# train.insert(18,'away_h2h',0)

# for i in range(0,len(train)):
#     a = train.iloc[:i]
#     home = train['home_id'][i]
#     away = train['away_id'][i]

#     try:
#         b = a[((a['home_id'] == home) & (a['away_id'] == away)) | 
#              ((a['away_id'] == home) & (a['home_id'] == away))]

#         if len(b) >= 5:
#             c = b.iloc[-5:].reset_index().drop('index',axis=1)

#             for j in range(0,5):
#                 if c['winner'][j] == train['home_id'][i]:
#                     train['home_h2h'][i] = train['home_h2h'][i] + 3
#                 elif c['winner'][j] == 0:
#                     train['home_h2h'][i] = train['home_h2h'][i] + 1
#                     train['away_h2h'][i] = train['away_h2h'][i] + 1
#                 else:
#                     train['away_h2h'][i] = train['away_h2h'][i] + 3

#         elif (len(b) < 5) & (len(b) > 0):
#             for j in range(0,5):
#                 if b['winner'][j] == train['home_id'][i]:
#                     train['home_h2h'][i] = train['home_h2h'][i] + 3
#                 elif b['winner'][j] == 0:
#                     train['home_h2h'][i] = train['home_h2h'][i] + 1
#                     train['away_h2h'][i] = train['away_h2h'][i] + 1
#                 else:
#                     train['away_h2h'][i] = train['away_h2h'][i] + 3

#         else:
#             pass

#     except KeyError as err:
#         pass

# train.head()

In [18]:

# test.insert(17,'home_h2h',0)
# test.insert(18,'away_h2h',0)

# for i in range(0,len(test)):
#     a = test.iloc[:i]
#     home = test['home_id'][i]
#     away = test['away_id'][i]

#     try:
#         b = a[((a['home_id'] == home) & (a['away_id'] == away)) | 
#              ((a['away_id'] == home) & (a['home_id'] == away))]

#         if len(b) >= 5:
#             c = b.iloc[-5:].reset_index().drop('index',axis=1)

#             for j in range(0,5):
#                 if c['winner'][j] == train['home_id'][i]:
#                     train['home_h2h'][i] = train[t]['home_h2h'][i] + 3
#                 elif c['winner'][j] == 0:
#                     train['home_h2h'][i] = train['home_h2h'][i] + 1
#                     train['away_h2h'][i] = train['away_h2h'][i] + 1
#                 else:
#                     train['away_h2h'][i] = train['away_h2h'][i] + 3

#         elif (len(b) < 5) & (len(b) > 0):
#             for j in range(0,5):
#                 if b['winner'][j] == train['home_id'][i]:
#                     train['home_h2h'][i] = train['home_h2h'][i] + 3
#                 elif b['winner'][j] == 0:
#                     train['home_h2h'][i] = train['home_h2h'][i] + 1
#                     train['away_h2h'][i] = train['away_h2h'][i] + 1
#                 else:
#                     train['away_h2h'][i] = train['away_h2h'][i] + 3

#         else:
#             pass

#     except KeyError as err:
#         pass

In [19]:
# train.to_csv('./train_1005.csv',index=False)
# test.to_csv('./test_1005.csv',index=False)
# test

### 맞대결 성적 추가

In [20]:
# 테스트 데이터에서 맞대결 하는 팀별 기록 추가

## 학습데이터
for t in range(0,len(test_list)):
    train_list[t].insert(17,'home_h2h',0)
    train_list[t].insert(18,'away_h2h',0)
    
    for i in range(0,len(train_list[t])):
        a = train_list[t].iloc[:i]
        home = train_list[t]['home_id'][i]
        away = train_list[t]['away_id'][i]

        try:
            b = a[((a['home_id'] == home) & (a['away_id'] == away)) | 
                 ((a['away_id'] == home) & (a['home_id'] == away))]

            if len(b) >= 5:
                c = b.iloc[-5:].reset_index().drop('index',axis=1)

                for j in range(0,5):
                    if c['winner'][j] == train_list[t]['home_id'][i]:
                        train_list[t]['home_h2h'][i] = train_list[t]['home_h2h'][i] + 3
                    elif c['winner'][j] == 0:
                        train_list[t]['home_h2h'][i] = train_list[t]['home_h2h'][i] + 1
                        train_list[t]['away_h2h'][i] = train_list[t]['away_h2h'][i] + 1
                    else:
                        train_list[t]['away_h2h'][i] = train_list[t]['away_h2h'][i] + 3
            
            elif (len(b) < 5) & (len(b) > 0):
                for j in range(0,5):
                    if b['winner'][j] == train_list[t]['home_id'][i]:
                        train_list[t]['home_h2h'][i] = train_list[t]['home_h2h'][i] + 3
                    elif b['winner'][j] == 0:
                        train_list[t]['home_h2h'][i] = train_list[t]['home_h2h'][i] + 1
                        train_list[t]['away_h2h'][i] = train_list[t]['away_h2h'][i] + 1
                    else:
                        train_list[t]['away_h2h'][i] = train_list[t]['away_h2h'][i] + 3
            
            else:
                pass

        except KeyError as err:
            pass
        
## 테스트 데이터
for t in range(0,len(test_list)):
    test_list[t].insert(14,'home_h2h',0)
    test_list[t].insert(14,'away_h2h',0)
    a = train_list[t]
    
    for i in range(0,len(test_list[t])):
        home = test_list[t]['home_id'][i]
        away = test_list[t]['away_id'][i]

        
        try:
            b = a[((a['home_id'] == home) & (a['away_id'] == away)) | 
                 ((a['away_id'] == home) & (a['home_id'] == away))]


            if len(b) >= 5:
                c = b.iloc[-5:].reset_index().drop('index',axis=1)

                for j in range(0,5):
                    if c['winner'][j] == test_list[t]['home_id'][i]:
                        test_list[t]['home_h2h'][i] = test_list[t]['home_h2h'][i] + 3
                    elif c['winner'][j] == 0:
                        test_list[t]['home_h2h'][i] = test_list[t]['home_h2h'][i] + 1
                        test_list[t]['away_h2h'][i] = test_list[t]['away_h2h'][i] + 1
                    else:
                        test_list[t]['away_h2h'][i] = test_list[t]['away_h2h'][i] + 3
            
            elif (len(b) < 5) & (len(b) > 0):
                for j in range(0,5):
                    if b['winner'][j] == test_list[t]['home_id'][i]:
                        test_list[t]['home_h2h'][i] = test_list[t]['home_h2h'][i] + 3
                    elif b['winner'][j] == 0:
                        test_list[t]['home_h2h'][i] = test_list[t]['home_h2h'][i] + 1
                        test_list[t]['away_h2h'][i] = test_list[t]['away_h2h'][i] + 1
                    else:
                        test_list[t]['away_h2h'][i] = test_list[t]['away_h2h'][i] + 3
            
            else:
                pass

        except KeyError as err:
            pass

## Training, Testing, Inserting To DB

In [21]:
# test_list[0]
# train_list[0]

In [22]:
# 일반 승무패 파이캐럿 돌리기
from pycaret.classification import *

# col = test_list[0].columns.to_list()[18:-1]
# input_var_h = col + ['home_result_pts']

input_var_h = ['home_h2h','away_h2h','home_possession_percent','away_possession_percent','home_xg','away_xg',
       'home_goals','away_goals','home_progressive_runs','away_progressive_runs',
       'home_touches_in_box','away_touches_in_box','home_shots_on_target','away_shots_on_target',
       'home_through_passes_successful','away_through_passes_successful',
       'home_pass_to_final_thirds_successful','away_pass_to_final_thirds_successful',
       'home_tackles','away_tackles','home_ppda','away_ppda','home_result_pts']

for i in range(0,len(test_list)):
    py_norm(train_list[i],test_list[i])
    
# py_norm(train_list[0],test_list[0])

In [23]:
# 핸디캡 파이캐럿 돌리기
from pycaret.classification import *

# col = test.columns.to_list()[18:-1]
# input_var_h = col + ['home_result_pts']

input_var_h = ['home_h2h','away_h2h','home_possession_percent','away_possession_percent','home_xg','away_xg',
       'home_goals','away_goals','home_progressive_runs','away_progressive_runs',
       'home_touches_in_box','away_touches_in_box','home_shots_on_target','away_shots_on_target',
       'home_through_passes_successful','away_through_passes_successful',
       'home_pass_to_final_thirds_successful','away_pass_to_final_thirds_successful',
       'home_tackles','away_tackles','home_ppda','away_ppda','home_result_pts']

for i in range(0,len(test_list)):
    py_handi(train_list[i],test_list[i],handi)

# py_handi(train_list[3],test_list[3],handi)

In [24]:
# handi[300:]
test_list[0].tail()

,area_id,area_name,competition_id,competition_name,season_id,season_name,round_id,round_name,matche_id,date,...,away_ppda,away_tackles,away_pass_to_final_thirds_successful,away_through_passes_successful,away_shots_on_target,away_touches_in_box,away_progressive_runs,away_goals,away_xg,away_possession_percent
0,250,France,412,Ligue 1,187374,2021/2022,4424444,Regular Season,5240910,2021-10-28 04:00:00,...,9.752751,5.925566,43.566343,2.372168,4.653722,16.265372,13.375405,1.563107,1.487266,55.495146

In [25]:
# 언더오버 파이캐럿 돌리기
from pycaret.regression import *

# col = test.columns.to_list()[18:-1]
# input_var_g = col + ['goals']

input_var_g = ['home_h2h','away_h2h','home_possession_percent','away_possession_percent','home_xg','away_xg',
       'home_progressive_runs','away_progressive_runs',
       'home_touches_in_box','away_touches_in_box','home_shots_on_target','away_shots_on_target',
       'home_through_passes_successful','away_through_passes_successful',
       'home_pass_to_final_thirds_successful','away_pass_to_final_thirds_successful',
       'home_tackles','away_tackles','home_ppda','away_ppda','home_goals','away_goals','goals']


for i in range(0,len(test_list)):
    py_unov(train_list[i],test_list[i],unov)

# py_unov(train_list[0],test_list[0],unov)

In [26]:
bot.sendMessage(chat_id, "[SUCCESS] 모델링-select-h2h 작업 완료.\n {}".format(d))

In [100]:
# len(test_list)

## Feature importance

In [101]:
# from pycaret.classification import *

# col = test_list[0].columns.to_list()[18:-1]

# # input_var_h = col + ['home_result_pts']
# from pycaret.classification import *

# input_var_h = ['h2h','home_possession_percent','away_possession_percent','home_xg','away_xg',
#        'home_goals','away_goals','home_progressive_runs','away_progressive_runs',
#        'home_touches_in_box','away_touches_in_box','home_shots_on_target','away_shots_on_target',
#        'home_through_passes_successful','away_through_passes_successful',
#        'home_pass_to_final_thirds_successful','away_pass_to_final_thirds_successful',
#        'home_tackles','away_tackles','home_ppda','away_ppda','home_result_pts']

# # for i in range(0,len(test_list)):
    
# setup_clf = setup(data = train_list[1][input_var_h], target = 'home_result_pts', silent = True)
# comp = compare_models()
# tune = tune_model(comp)
# #     pred = predict_model(tune,data=test_list[i],raw_score=True)

# plot_model(estimator = tune, plot = 'feature') 

# py_norm(train_list[0],test_list[0])

In [102]:
# from pycaret.classification import *

# setup_clf = setup(data = train_list[3][input_var_h], target = 'home_result_pts', silent = True,
#                          normalize = True, normalize_method = 'robust')
# comp = compare_models(sort='Accuracy',n_select=1)
# tune = tune_model(comp,optimize='Accuracy')
# pred = predict_model(tune,data=test_list[3],raw_score=True)

# plot_model(estimator = tune, plot = 'feature')

## Checking result

In [144]:
# 실제 경기와 비교하여 적중률 확인

## 앞에서 쌓은 모델 데이터 연결, 불러오기
db_connection_str ='-'
db_connection = create_engine(db_connection_str)

model = pd.read_sql('''
                    SELECT *
                    FROM model
                ''', \
                     con=db_connection)

# model = model.iloc[-68:].reset_index().drop('index',axis=1)

# AWS wyscout 데이터에서 match_info 데이터 연결, 불러오기
db_connection_str = '-'
db_connection = create_engine(db_connection_str)

# pymysql 에서 날짜형식 사용할 때 %% 두번쓰기
info = pd.read_sql('''
                    SELECT matche_id,winner
                    FROM view_match_info
                    WHERE (competition_id = 551 OR competition_id = 534 OR 
                    competition_id = 795 OR competition_id = 524 OR competition_id = 426 OR
                    competition_id = 412 OR competition_id = 364)  AND status = 'Played'

                ''', \
                     con=db_connection)

# info['date'] = dt.date(info['date'])


# for i in range(len(info)):
#     info['date'][i] = str(info['date'][i])
# #     info['date'][i] = dt.date(info['date'][i])

# print(type(info['date']))
# info.tail()


test = pd.merge(model, info, how = 'left', left_on = 'match_id', right_on = 'matche_id')
test = test[test['winner'].notna()]
# test.head()
# test.tail()

raw = test[['match_id','competition_id','season_id', 'date','home_id','away_id',
               'category','model_name','label','score_lose','score_draw','score_win','winner']].reset_index().drop('index',axis=1)

# raw.head()
# ## 실제 경기 결과에 따라 홈 승점으로 표현
raw.insert(12,'Label_result',0)

for i in range(0,len(raw)):
    if raw['winner'][i] == 0:
        raw['Label_result'][i] = 1.0
    elif raw['winner'][i] == raw['home_id'][i]:
        raw['Label_result'][i] = 3.0
    elif raw['winner'][i] == raw['away_id'][i]:
        raw['Label_result'][i] = 0.0

# raw

## 핸디캡, 언더오버는 정확한 적중률 확인하기 어려우므로 일반 승무패만 확인
num = 0
for i in range(0,len(raw[raw['category'] == 'normal'])):
    if raw['label'][i] == raw['Label_result'][i]:
        num += 1
    else:
        pass

percentage = (num / len(raw[raw['category'] == 'normal']) * 100)
percentage
bot.sendMessage(chat_id, "[SUCCESS] 맞대결 성적까지 넣었을 때 적중률은? {}경기 중 {}경기 적중, {}%".format( len(raw[raw['category'] == 'normal']), num, percentage))

## 조합픽

In [104]:
# 배당률 데이터 하나로 합치기
norm['base_line'] = 0
norm['category'] = 'normal'

handi['draw_odd'] = 0
handi['category'] = 'handicap'

odd_concat = pd.concat([norm,handi],axis=0).reset_index(drop=True)
odd_concat

,date,league_id,league,home,away,status,home_odd,away_odd,draw_odd,base_line,category
0,2021-05-21,207,Primera Division,Levante,Cadiz,3.0,1.68,4.80,4.2,0.00,normal
1,2021-05-22,123,Bundesliga,Bayern München,Augsburg,3.0,1.13,16.00,10.5,0.00,normal
2,2021-05-22,123,Bundesliga,Borussia Dortmund,Bayer Leverkusen,3.0,1.56,5.10,4.9,0.00,normal
3,2021-05-22,123,Bundesliga,Köln,Schalke 04,3.0,1.37,6.80,5.6,0.00,normal
4,2021-05-22,123,Bundesliga,Eintracht Frankfurt,Freiburg,3.0,2.14,3.00,4.2,0.00,normal
...,...,...,...,...,...,...,...,...,...,...,...
782,2021-10-18 00:00:00,207,Primera Division,villarreal,osasuna,NaN,1.82,2.17,0.0,-0.75,handicap
783,2021-10-19 00:00:00,94,England Premire League,arsenal,crystal palace,NaN,1.88,2.09,0.0,-0.75,handicap
784,2021-10-19 00:00:00,207,Primera Division,cd alaves,real betis,NaN,2.07,1.89,0.0,0.25,handicap
785,2021-10-19 00:00:00,207,Primera Division,espanyol,cadiz,NaN,1.91,2.05,0.0,-0.75,handicap
786,2021-10-19 00:00:00,199,Serie A,venezia,fiorentina,NaN,2.06,1.90,0.0,0.50,handicap

In [105]:
# 모델 데이터 한 번 돌아갈 때 마다 자르기
cut = []

for i in range(1,len(model)):
#     if i < len(model):
    if (model['category'][i-1] == 'under over') & (model['category'][i] == 'normal'):
        cut.append(i)
    else:
        pass
    
# cut

# 잘라낸 모델에서 가장 확률 높은 순위
model_new = model[-(len(model)-cut[-1:][0]):].reset_index().drop('index',axis=1)

model_new = model.copy()
model_new.insert(16, 'High_Score',0.0000)

for i in range(0,len(model_new)):
    if (model_new['Score_0'][i] > model_new['Score_1'][i]) & (model_new['Score_0'][i] > model_new['Score_3'][i]):
        model_new['High_Score'][i] = model_new['Score_0'][i]
    
    elif (model_new['Score_1'][i] > model_new['Score_0'][i]) & (model_new['Score_1'][i] > model_new['Score_3'][i]):
        model_new['High_Score'][i] = model_new['Score_1'][i]
        
    elif (model_new['Score_3'][i] > model_new['Score_0'][i]) & (model_new['Score_3'][i] > model_new['Score_1'][i]):
        model_new['High_Score'][i] = model_new['Score_3'][i]
        
model_new['date'] = model_new['date'].dt.date
model_new

,match_id,competition_id,competition,season,date,home,away,home_id,away_id,Label,category,base_line,model_name,Score_0,Score_1,Score_3,High_Score,season_id
0,5234829,364,Premier League,2021/2022,2021-08-24,West Ham United,Leicester City,1633,1631,1.000000,normal,0,LogisticRegression,0.0904,0.8729,0.0368,0.8729,NaN
1,5198073,534,J1 League,2021,2021-08-25,Consadole Sapporo,Nagoya Grampus,12823,12801,1.000000,normal,0,LGBMClassifier,0.0094,0.9766,0.0140,0.9766,NaN
2,5198074,534,J1 League,2021,2021-08-25,Vegalta Sendai,Tokyo,12820,12806,1.000000,normal,0,LGBMClassifier,0.0161,0.9639,0.0200,0.9639,NaN
3,5198075,534,J1 League,2021,2021-08-25,Urawa Reds,Sanfrecce Hiroshima,12799,12810,3.000000,normal,0,LGBMClassifier,0.0018,0.0578,0.9404,0.9404,NaN
4,5198076,534,J1 League,2021,2021-08-25,Yokohama,Gamba Osaka,12817,12803,1.000000,normal,0,LGBMClassifier,0.0125,0.9655,0.0221,0.9655,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852,5241421,795,LaLiga,2021/2022,2021-10-17,Rayo Vallecano,Elche,713,702,2.363456,under over,2,LinearRegression,0.0000,0.0000,0.0000,0.0000,187526.0
853,5241420,795,LaLiga,2021/2022,2021-10-17,Real Sociedad,Mallorca,687,686,2.576268,under over,2,LinearRegression,0.0000,0.0000,0.0000,0.0000,187526.0
854,5241414,795,LaLiga,2021/2022,2021-10-18,Barcelona,Valencia,676,674,3.982309,under over,3,LinearRegression,0.0000,0.0000,0.0000,0.0000,187526.0
855,5241422,795,LaLiga,2021/2022,2021-10-18,Villarreal,Osasuna,682,681,2.624563,under over,2,LinearRegression,0.0000,0.0000,0.0000,0.0000,187526.0
856,5234888,364,Premier League,2021/2022,2021-10-16,Southampton,Leeds United,1619,1630,2.651028,under over,3,LinearRegression,0.0000,0.0000,0.0000,0.0000,187475.0

In [106]:
concat = pd.merge(model_new,odd_concat, how='inner',on=['date','home','away','category'])
concat = concat.drop(['base_line_y','league_id','league','status'],axis=1)
concat

,match_id,competition_id,competition,season,date,home,away,home_id,away_id,Label,...,base_line_x,model_name,Score_0,Score_1,Score_3,High_Score,season_id,home_odd,away_odd,draw_odd
0,5234829,364,Premier League,2021/2022,2021-08-24,West Ham United,Leicester City,1633,1631,1.0,...,0,LogisticRegression,0.0904,0.8729,0.0368,0.8729,NaN,2.49,2.90,3.4
1,5234830,364,Premier League,2021/2022,2021-08-28,Manchester City,Arsenal,1625,1609,3.0,...,0,LogisticRegression,0.0006,0.4565,0.5429,0.5429,NaN,1.34,9.60,5.2
2,5234831,364,Premier League,2021/2022,2021-08-28,Aston Villa,Brentford,1614,1669,1.0,...,0,LogisticRegression,0.2144,0.7683,0.0173,0.7683,NaN,1.96,4.20,3.5
3,5234833,364,Premier League,2021/2022,2021-08-28,Newcastle United,Southampton,1613,1619,1.0,...,0,LogisticRegression,0.0216,0.8366,0.1418,0.8366,NaN,2.46,2.90,3.5
4,5234835,364,Premier League,2021/2022,2021-08-28,West Ham United,Crystal Palace,1633,1628,1.0,...,0,LogisticRegression,0.0049,0.7396,0.2555,0.7396,NaN,1.56,6.50,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,5241414,795,LaLiga,2021/2022,2021-10-18,Barcelona,Valencia,676,674,3.0,...,0,LogisticRegression,0.0000,0.0964,0.9036,0.9036,187526.0,1.56,6.00,4.3
165,5241415,795,LaLiga,2021/2022,2021-10-17,Celta de Vigo,Sevilla,692,680,1.0,...,0,LogisticRegression,0.2053,0.7804,0.0142,0.7804,187526.0,3.50,2.29,3.2
166,5241418,795,LaLiga,2021/2022,2021-10-17,Levante,Getafe,695,698,1.0,...,0,LogisticRegression,0.0246,0.8534,0.1219,0.8534,187526.0,2.50,3.40,2.9
167,5241420,795,LaLiga,2021/2022,2021-10-17,Real Sociedad,Mallorca,687,686,1.0,...,0,LogisticRegression,0.0102,0.7300,0.2598,0.7300,187526.0,1.44,8.30,4.4
168,5241422,795,LaLiga,2021/2022,2021-10-18,Villarreal,Osasuna,682,681,1.0,...,0,LogisticRegression,0.0107,0.7548,0.2345,0.7548,187526.0,1.62,6.10,3.9

In [107]:
test = concat.copy()
test.insert(10,'odd',0.0000)

for i in range(0,len(test)):
    if test['category'][i] == 'normal':
        if test['Label'][i] == 0:
            test['odd'][i] = test['away_odd'][i]
            
        elif test['Label'][i] == 1:
            test['odd'][i] = test['draw_odd'][i]
            
        elif test['Label'][i] == 3:
            test['odd'][i] = test['home_odd'][i]
            
            
    elif test['category'][i] == 'handicap':
        if test['Label'][i] == 0:
            test['odd'][i] = test['away_odd'][i]
            
        elif test['Label'][i] == 1:
            test['odd'][i] = test['draw_odd'][i]
            
        elif test['Label'][i] == 3:
            test['odd'][i] = test['home_odd'][i]
            
test = test[['match_id', 'competition', 'season', 'date', 'home', 'away', 'Label',
       'category', 'base_line_x', 'High_Score','odd']]
test.columns = ['match_id', 'competition', 'season', 'date', 'home', 'away', 'Label',
       'category', 'base_line', 'High_Score','odd']

# test

#최종 배당률 계산 함수

def multiply_f(arr):

    ans = 1
    for n in arr:
        if n == 0:
            return 0
        ans *= n
    return ans

In [108]:
test = test[test['date'] > dt.date.today()]

### 안전형

In [109]:
safe = test.sort_values(by='High_Score',ascending = False)[:5].reset_index(drop=True)

safe.insert(11,'result','')
safe.insert(0,'summary','')

for i in range(0,len(safe)):
    if safe['Label'][i] == 0:
        safe['result'][i] = 'Away Win'
        
    elif safe['Label'][i] == 1:
        safe['result'][i] = 'Draw'
        
    elif safe['Label'][i] == 3:
        safe['result'][i] = 'Home Win'
    
    a = ['(', safe['category'][i],')',safe['date'][i].strftime('%Y-%m-%d') , ' ', safe['home'][i] ,' VS ' ,
         safe['away'][i], ' - ',safe['result'][i]]
    
    safe['summary'][i] = ''.join(a)
    
safe

multiply = multiply_f(safe['odd'])

In [110]:

summ = ['',safe['summary'][0],safe['summary'][1],safe['summary'][2],safe['summary'][3],safe['summary'][4],
        '[예상 배당률] '+str(multiply)]
text = '\n'.join(summ)

# print(text)

bot.sendMessage(chat_id, "[조합픽-안전] {}".format(text))

KeyError: 0

### 고배당

In [ ]:
risk = test.sort_values(by='odd',ascending = False)[:5].reset_index(drop=True)

risk.insert(11,'result','')
risk.insert(0,'summary','')

for i in range(0,len(risk)):
    if risk['Label'][i] == 0:
        risk['result'][i] = 'Away Win'
        
    elif risk['Label'][i] == 1:
        risk['result'][i] = 'Draw'
        
    elif risk['Label'][i] == 3:
        risk['result'][i] = 'Home Win'
    
    a = ['(', risk['category'][i],')',risk['date'][i].strftime('%Y-%m-%d') , ' ', risk['home'][i] ,' VS ' ,
         risk['away'][i], ' - ',risk['result'][i]]
    
    risk['summary'][i] = ''.join(a)
    
multiply2 = multiply_f(risk['odd'])

In [ ]:
try:
    
    summ = ['',risk['summary'][0],risk['summary'][1],risk['summary'][2],risk['summary'][3],risk['summary'][4],
            '[예상 배당률] '+str(multiply2)]
    text = '\n'.join(summ)
    # print(text)
    bot.sendMessage(chat_id, "[조합픽-고배당] {}".format(text))

except KeyError as err:
    
    try:
        summ = ['',risk['summary'][0],risk['summary'][1],risk['summary'][2],risk['summary'][3],
                '[예상 배당률] '+str(multiply2)]
        text = '\n'.join(summ)
        # print(text)
        bot.sendMessage(chat_id, "[조합픽-고배당] {}".format(text))
    
    except KeyError as err2:
        
        try:
    
            summ = ['',risk['summary'][0],risk['summary'][1],risk['summary'][2],
                    '[예상 배당률] '+str(multiply2)]
            text = '\n'.join(summ)
            # print(text)
            bot.sendMessage(chat_id, "[조합픽-고배당] {}".format(text))
        
        except KeyError as err3:
            
            pass

### AI PICK

In [ ]:
ai = test[test['odd'] > 2].sort_values(by='odd',ascending = False)[:5].reset_index(drop=True)
multiply3 = multiply_f(ai['odd'])

In [ ]:
ai.insert(11,'result','')
ai.insert(0,'summary','')

for i in range(0,len(ai)):
    if ai['Label'][i] == 0:
        ai['result'][i] = 'Away Win'
        
    elif ai['Label'][i] == 1:
        ai['result'][i] = 'Draw'
        
    elif ai['Label'][i] == 3:
        ai['result'][i] = 'Home Win'
    
    a = ['(', ai['category'][i],')',ai['date'][i].strftime('%Y-%m-%d') , ' ', ai['home'][i] ,' VS ' ,
         ai['away'][i], ' ',' - ',ai['result'][i]]
    
    ai['summary'][i] = ''.join(a)

In [ ]:
try:
    summ = ['',ai['summary'][0],ai['summary'][1],ai['summary'][2],ai['summary'][3],ai['summary'][4],
            '[예상 배당률] '+str(multiply3)]
    text = '\n'.join(summ)
    bot.sendMessage(chat_id, "[조합픽-AI픽] {}".format(text))

except KeyError as err:
    
    try:
        summ = ['',ai['summary'][0],ai['summary'][1],ai['summary'][2],ai['summary'][3],
                '[예상 배당률] '+str(multiply3)]
        text = '\n'.join(summ)
        bot.sendMessage(chat_id, "[조합픽-AI픽] {}".format(text))
    
    except KeyError as err2:
        
        try:
            summ = ['',ai['summary'][0],ai['summary'][1],ai['summary'][2],
                    '[예상 배당률] '+str(multiply3)]
            text = '\n'.join(summ)
            bot.sendMessage(chat_id, "[조합픽-AI픽] {}".format(text))
        
        except KeyError as err3:
            pass